---
datacenter: "dc1"
consul:
  ui: "true"
  bootstrap_expect: "1"
  bootstrap_token_output_dir: /vagrant/ansible/secrets
  bootstrap_token_local_output_file: secrets/consul-secrets.txt
  client_addr: "0.0.0.0"
  advertise_int: eth1 # or use advertise_addr: '172.16.1.11'
  servers:
    - 172.16.1.11
  data_dir: /opt/consul
  log_level: "INFO"
  disable_remote_exec: "false"
  enable_script_checks: "true"
  enable_local_script_checks: "true"
  acl:
    enable: true
    default_policy: "allow"
    enable_token_persistence: "true"
  telemetry:
    enable: true
    dogstatsd_addr: "172.20.1.1:8125"
    disable_hostname: "false"
vault:
  ui: "true"
  bootstrap_token_output_dir: /vagrant/ansible/secrets
  bootstrap_token_local_output_file: secrets/vault-secrets.json
  bootstrap:
    secret_shares: 5
    secret_threshold: 3
  api:
    scheme: http
    address: "{{ ansible_eth1.ipv4.address }}"
    port: "8200"
  listerner_address: "0.0.0.0"
  listerner_port: "8200"
  tls_disable: "true"
  # file:
  #   enable: true
  #   path: /mnt/vault/data
  consul:
    enable: true
    scheme: http
    address: localhost
    port: 8500
    path: vault/
  telemetry:
    enable: true
    type: statsd # or prometheus
    system_addr: "172.20.1.1" # Only needed for statsd
    system_port: "8125" # Only needed for statsd
    disable_hostname: false # Only needed for prometheus
  agent:
    scheme: http
    server: 172.16.1.21
    port: 8200
    use_auto_auth_token: "true"
    auth_file_path: /home/vagrant/vault-token-via-agent
    listener:
      address: 127.0.0.1
      port: 8100
      tls_disable: "true"
nomad:
  common:
    data_dir: /opt/nomad
    log_level: "INFO"
    advertise:
      interface: "eth1"
    consul:
      enable: true
      address: 127.0.0.1
      port: 8500
      auto_advertise: "true"
      server_auto_join: "true"
  server:
    bootstrap_expect: "1"
    bind_addr: "0.0.0.0"
    client:
      enable: true
      network_interface: "eth1"
    plugin:
      exec: true
  client:
    network_interface: "eth1"
    servers:
      - 172.16.1.31
    meta:
    - owner: IT
    - service: web
    - rack: "rack-12-1"
    plugin:
      exec: true
      docker: true
web:
  config_dir: /opt/config
lb:
  config_dir: /opt/config
consul_template:
  config_dir: /opt/consul-template
  version: 0.25.1
  templates_dir: /opt/consul-template/templates
  handlers_dir: /opt/consul-template/handlers
